### ISSUE TITLE
error

### ISSUE THREAD

**Issue by abhigenie92** [the-useless-one/hide_my_python#12]
```
abhishek:~/Desktop/work/gits/hide_my_python$ python3 ./hide_my_python.py -o hello.txt
Traceback (most recent call last):
  File "./hide_my_python.py", line 61, in <module>
    main()
  File "./hide_my_python.py", line 46, in main
    for proxy in parser.generate_proxy(args):
  File "/home/abhishek/Desktop/work/gits/hide_my_python/parser.py", line 145, in generate_proxy
    yield parse_proxy(proxy_html)
  File "/home/abhishek/Desktop/work/gits/hide_my_python/parser.py", line 56, in parse_proxy
    ip_port_html = regex.IP_PORT_HTML.search(proxy_html).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by klvs** [comment]
- 1

**Comment by Mice7R** [comment]
I fixed a few days ago.
here is the pull request: https://github.com/the-useless-one/hide_my_python/pull/11.

**Comment by llazzaro** [comment]
I tested this pr and it is working for me. thanks

**Comment by nadtoka** [comment]
Looks like the issue is still there

**Comment by klvs** [comment]
It is forever broken.

**Comment by nadtoka** [comment]
Yeah I understood already that the project was left...

2016-11-29 23:31 GMT+02:00 Alex Roman <notifications@github.com>:

**Comment by Mice7R** [comment]
Yes the owner seems to have forgotten about this repo. But as long as the
patch works and no more things break it'll be fine.

**Comment by klvs** [comment]
@nadtoka Sorry, I meant that somewhat jokingly. I don't know what you're using proxies for and am sure you know what you're doing. If it's of any use, when I found myself at this repo, I eventually wrote my own (albeit very hacky) scrapper and found that the HMA public proxies died far to quickly (usually no more than 10-30s if at all) for my use. Some people claim to have success with public proxies. I am not one. luminati.io is as expensive as it is good. I ended up hosting my own.

Sorry to go on a tangent here, just felt bad that someone had maybe interpreted my comment negatively and hoped to drop in some wisdom incase you didn't have your heart set on HMA.
