### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by nadtoka** [the-useless-one/hide_my_python#13]
How to fix this? also it looks like README file has no inforation about dependencies. I installed manually missing modules through pip but still no luck( when Help works but when run parses gettings this error

[root@HH-Beast proxy]# ./hide_my_python.py -pr {http,https} -ka -aa -s -c -v -o proxy.list
[info] number of proxies: all
[info] countries: ['China', 'Indonesia', 'United States', 'Brazil', 'Venezuela'] and 88 more
[info] ports: all
[info] protocols: ['https', 'http']
[info] anonymity: ['Medium', 'High', 'High +KA']
[info] speed: ['Medium', 'High']
[info] connection time: ['Medium', 'High']
[info] retrieved 1 proxiesTraceback (most recent call last):
  File "./hide_my_python.py", line 61, in <module>
    main()
  File "./hide_my_python.py", line 46, in main
    for proxy in parser.generate_proxy(args):
  File "/var/www/api.mangahaven.org/http/proxy/parser.py", line 145, in generate_proxy
    yield parse_proxy(proxy_html)
  File "/var/www/api.mangahaven.org/http/proxy/parser.py", line 56, in parse_proxy
    ip_port_html = regex.IP_PORT_HTML.search(proxy_html).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by aorzh** [comment]
It is fixed in #11 and #14 pull requests. Fill free to use forked repositories.
