### ISSUE TITLE
KeyError: "name='PHPSESSID', domain=N

### ISSUE THREAD

**Issue by josefson** [the-useless-one/hide_my_python#4]
Today the software is not working showing this error:

```
Traceback (most recent call last):
  File "/Users/josefson/Applications/hide_my_python/hide_my_python.py", line 61, in <module>
    main()
  File "/Users/josefson/Applications/hide_my_python/hide_my_python.py", line 46, in main
    for proxy in parser.generate_proxy(args):
  File "/Users/josefson/Applications/hide_my_python/parser.py", line 106, in generate_proxy
    cookies = {'PHPSESSID' : r.cookies['PHPSESSID']}
  File "/usr/local/lib/python3.4/site-packages/requests/cookies.py", line 276, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.4/site-packages/requests/cookies.py", line 331, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='PHPSESSID', domain=N
```

**Comment by aorzh** [comment]
Hi there
http://proxylist.hidemyass.com no londer available so I wrote simple gist for getting proxies on a fly from other resource:
https://gist.github.com/aorzh/7c37bf7da5dc062901a4f06bc9fecd5d
